# Import the numpy package under the name np

In [ ]:
import numpy as np


# Create a null vector of size 10

In [59]:
a1_d = np.arange(10)

# Create a vector with values ranging from 10 to 49

In [60]:
darray = np.arange(10,49)


# Find the shape of previous array in question 3

In [67]:
darray_shape =darray.shape
print(darray_shape)

(39,)


# Print the type of the previous array in question 3

In [65]:
print(darray.dtype)

int32


# Print the numpy version and the configuration

In [66]:
print(np.__version__)

1.18.1


# Print the dimension of the array in question 3

In [68]:
darray_dim = darray.ndim
print(darray_dim)


1


# Create a boolean array with all the True values

In [72]:
arr_bool = np.array(['true','true','true'],dtype='bool')

# Create a two dimensional array

In [45]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [46]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
arr2.ndim

2

In [50]:
arr2.shape

(2, 4)

In [51]:
arr2.dtype

dtype('int32')

In [52]:
data1 = [6,4,5.7,3]
arr1 = np.array(data1)

In [53]:
arr1

array([6. , 4. , 5.7, 3. ])

In [54]:
arr1.dtype

dtype('float64')

In [55]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.empty((2,3,2))

array([[[8.02682902e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23059725e-307, 1.39403271e+165]],

       [[1.64858618e+185, 5.69501343e-066],
        [7.96525079e-042, 3.11151385e+179],
        [3.98185283e-062, 5.26437080e-037]]])