# Import the numpy package under the name np

In [3]:
import numpy as np


# Create a null vector of size 10

In [59]:
a1_d = np.arange(10)

# Create a vector with values ranging from 10 to 49

In [60]:
darray = np.arange(10,49)


# Find the shape of previous array in question 3

In [67]:
darray_shape =darray.shape
print(darray_shape)

(39,)


# Print the type of the previous array in question 3

In [65]:
print(darray.dtype)

int32


# Print the numpy version and the configuration

In [66]:
print(np.__version__)

1.18.1


# Print the dimension of the array in question 3

In [68]:
darray_dim = darray.ndim
print(darray_dim)


1


# Create a boolean array with all the True values

In [72]:
arr_bool = np.array(['true','true','true'],dtype='bool')

# Create a two dimensional array

In [45]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [46]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [47]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
arr2.ndim

2

In [50]:
arr2.shape

(2, 4)

In [51]:
arr2.dtype

dtype('int32')

In [16]:
data1 = [6,4,5.7,3]
arr1 = np.array(data1)

In [53]:
arr1

array([6. , 4. , 5.7, 3. ])

In [54]:
arr1.dtype

dtype('float64')

In [55]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.empty((2,3,2))

array([[[8.02682902e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [6.23059725e-307, 1.39403271e+165]],

       [[1.64858618e+185, 5.69501343e-066],
        [7.96525079e-042, 3.11151385e+179],
        [3.98185283e-062, 5.26437080e-037]]])

In [4]:
arr = np.arange(10)
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [5]:
array_slice = arr[5:8]

In [7]:
array_slice


array([12, 12, 12])

In [8]:
array_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [9]:
array_slice[5:8]


array([], dtype=int32)

In [10]:
array_slice[:]

array([   12, 12345,    12])

In [11]:
arr_slice = array_slice
arr_slice

array([   12, 12345,    12])

In [12]:
arr_slice[1]=6
arr_slice

array([12,  6, 12])

In [13]:
array_slice

array([12,  6, 12])

#Create a three dimensional array

In [14]:
arr3d = [[[1,2,3],[4,5,6],[7,8,9]]]
arr3d

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

#Reverse a vector (first element becomes last)

In [17]:
data1

[6, 4, 5.7, 3]

In [21]:
np.flip(data1)

array([3. , 5.7, 4. , 6. ])

#Create a null vector of size 10 but the fifth value which is 1

In [25]:
data2 = np.zeros(10)
data2[5]  = 1
data2

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#Create a 3x3 identity matrix

In [26]:
data3 = np.identity(3)
data3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#arr = np.array([1, 2, 3, 4, 5])
#Convert the data type of the given array from int to float

In [29]:
arr = np.array([1,2,3,4,5])
arr = arr.astype('float')
print(arr.dtype)

float64


In [30]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
#Multiply arr1 with arr2
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [31]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
#Make an array by comparing both the arrays provided above
print(arr1> arr2)

[[ True False  True]
 [False  True False]]


In [33]:
#Extract all odd numbers from arr with values(0-9)
arr_odd = np.arange(0,10,1)
arr_odd[arr_odd%2 != 0]

array([1, 3, 5, 7, 9])

#Replace all odd numbers to -1 from previous array

In [34]:
arr_odd[arr_odd%2 != 0] = -1

In [35]:
arr_odd

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [41]:
arr = np.arange(10)
#Replace the values of indexes 5,6,7 and 8 to 12
arr[5:10]=(8,9,10,11,12)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  8,  9, 10, 11, 12])

In [44]:
#Create a 2d array with 1 on the border and 0 inside
arr2d=np.array([[1,0,1],[1,0,1]])
arr2d

array([[1, 0, 1],
       [1, 0, 1]])

In [45]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#Convert all the values of 1st array to 64

In [48]:
arr3d[0][0]=64
arr3d[0][1]=64

In [49]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [62]:
array2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
#array2d.reshape(2,2)
array2d[0:1]

array([[0, 1, 2]])

#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [63]:
array2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
array2d[0:1]


array([[0, 1, 2]])

In [68]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
array2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
array2d[2,0]

6

In [78]:
#Create a 10x10 array with random values and find the minimum and maximum values
new_arr = np.arange(0,100).reshape(10,10)
new_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])